//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleEastCollege {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiddleEastCollege.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        public static string Complaint {
            get {
                return ResourceManager.GetString("Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Type.
        /// </summary>
        public static string ComplaintType {
            get {
                return ResourceManager.GetString("ComplaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENG.
        /// </summary>
        public static string ENG {
            get {
                return ResourceManager.GetString("ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry.
        /// </summary>
        public static string Enquiry {
            get {
                return ResourceManager.GetString("Enquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save.
        /// </summary>
        public static string ErrorInSave {
            get {
                return ResourceManager.GetString("ErrorInSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grievance.
        /// </summary>
        public static string Grievance {
            get {
                return ResourceManager.GetString("Grievance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Success.
        /// </summary>
        public static string SavedSuccess {
            get {
                return ResourceManager.GetString("SavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Data.
        /// </summary>
        public static string StudentData {
            get {
                return ResourceManager.GetString("StudentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Name.
        /// </summary>
        public static string TeacherName {
            get {
                return ResourceManager.GetString("TeacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student supporet service system.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
