//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleEastCollege.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentID { get; set; }
        public string StudentData { get; set; }
        public string StudentID { get; set; }
        public string Section { get; set; }
        public string TeacherName { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
    }
}
