//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleEastCollege.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public long ComplaintID { get; set; }
        public string StudentName { get; set; }
        public long StudentID { get; set; }
        public long ComplaintType { get; set; }
        public string Subject { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
    }
}
